import { Link } from "react-router-dom";

export default function DisclaimerPage() {
    return (
        <div className="pt-20 min-h-screen bg-neutral-50">
            <div className="container mx-auto px-4 py-12 max-w-3xl">
                <h1 className="text-3xl font-bold mb-4">AI Platform Disclaimer</h1>
                <p className="text-base text-neutral-600 mb-4">
                    Personas is an experimental AI platform. The conversational experiences and persona responses are generated by large language
                    models that can hallucinate facts, misunderstand prompts, or otherwise provide inaccurate or incomplete information.
                </p>

                <ul className="space-y-3 text-sm text-neutral-700 list-disc pl-6">
                    <li>
                        Content is provided for exploratory and educational purposes only. You remain fully responsible for verifying any
                        recommendations or statements before acting on them.
                    </li>
                    <li>
                        We do not make any guarantees about the accuracy, reliability, or suitability of the AI-generated content for your specific
                        use case.
                    </li>
                    <li>
                        By using this platform you acknowledge that hallucinations, bias, and other unexpected behaviors can occur, and that we are
                        not liable for any direct or indirect losses, damages, or regulatory issues that stem from using these outputs.
                    </li>
                    <li>Do not share sensitive or confidential information. Inputs may be logged for debugging, safety, or product improvements.</li>
                </ul>

                <div className="mt-8 text-sm text-neutral-600">
                    <p>
                        If you disagree with these terms, please discontinue use of the Personas experience. For questions, contact your platform
                        administrator.
                    </p>
                </div>

                <div className="mt-10 text-center">
                    <Link to="/" className="inline-flex items-center px-4 py-2 rounded-lg border text-sm font-medium hover:bg-neutral-100">
                        Return to dashboard
                    </Link>
                </div>
            </div>
        </div>
    );
}
